### ISSUE TITLE
Fix updater.py

### ISSUE THREAD

**Issue by GabrielHogan** [ZJX-ARTCC/jacksonville-issue-tracker#5]
**Describe the bug**
Brin broke it when he tried to add the ZZN check to the roster update.

**Log:**
`Job "update_roster (trigger: interval[0:30:00], next run at: 2020-10-16 07:43:04 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/zjxartcc_website/passenger/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/zjxartcc_website/passenger/zjxartcc.org/apps/user/updater.py", line 75, in update_roster
    if(user_details.facility.id == "ZZN"):
AttributeError: 'dict' object has no attribute 'facility'`

**Additional context**
None Currently Available

**Comment by brinbrody** [comment]
Syntax error because Brin is the big stupid. Fix hath been pushed.
